### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by bhawandeepsingh** [google/vizier#1021]
HI,
I keep getting the below error - 

`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO owners (owner_name) VALUES (?)]`

I get this error in every run.
I am not doing anything out of ordinary to the best of my knowledge.
I have tried setting busy timeout and lock timeout but neither has helped. 

Can you please help with what I am doing wrong here and how I can solve this ? Thanks

**Comment by xingyousong** [comment]
Hi, can you give us a minimal example to reproduce this error? I'm wondering if your application is too concurrent-intensive: https://stackoverflow.com/questions/3172929/operationalerror-database-is-locked

So far, all of our unit tests pass, so we haven't encountered this error before.

**Comment by bhawandeepsingh** [comment]
Thanks @xingyousong 
I am using the simple cookie example from vizier demo (code below).

```
from vizier import service
from vizier.service import clients
from vizier.service import pyvizier as vz

problem = vz.ProblemStatement()
problem.search_space.root.add_float_param('chocolate', 0.0, 1.0)
problem.metric_information.append(vz.MetricInformation(name='taste', goal=vz.ObjectiveMetricGoal.MAXIMIZE))

def evaluate(chocolate: float) -> float:
	return 1-2*(chocolate -.3)**2
	
study_config = vz.StudyConfig.from_problem(problem)
study_config.algorithm = 'GAUSSIAN_PROCESS_BANDIT'  

study_client = clients.Study.from_study_config(study_config, owner='bhawandeepsingh', study_id='cookie_study_0')
print('****************Local SQL database file located at: ', service.VIZIER_DB_PATH)

for _ in range(1) :
	suggestions = study_client.suggest(count=1)
	for suggestion in suggestions :
		chocolate = suggestion.parameters['chocolate']
		objective = evaluate(chocolate)
		print (chocolate, objective)
		final_measurement = vz.Measurement({'taste': objective})
		suggestion.complete(final_measurement)
```

I am using Ubuntu 22.04 and Python 3.10.12
Please let me know if any additional information can help you to find the root cause and I will provide it. Thanks

**Comment by xingyousong** [comment]
I just tried your code in colab (after installing with `!pip install google-vizier[jax]`) and everything worked fine. Can you make sure you have a fresh install (and even fresh colab kernel) when you execute that code snippet?

**Comment by sagipe** [comment]
The Vizier server is using an in memory SQLITE database, so restarting the Colab runtime should solve this issue, or a fresh Colab runtime as Richard suggested above.
Best,
Sagi

**Comment by bhawandeepsingh** [comment]
Works in collab as specified.
