### ISSUE TITLE
How to run "evaluate" function offline ?

### ISSUE THREAD

**Issue by bhawandeepsingh** [google/vizier#1026]
Hi,

In my code my "evaluate" function is not runnable with new suggestion automatically in python code.
I need to go to a C++ file, look for #defines under #defines under #ifdefs etc, update the define values per the suggestion, run my code and then I get the result of the "evaluate" function. So far, I do not know a way to automate or script it. I run it offline.  
How can I handle this ? 
Basically what I need is - 
1. I provide the range of valid values for parameters (+ some results from previous runs) and run vizier 
2. vizier makes a suggestion and updates it's database
3. I use the suggestion, run my test with it offline, get the evaluate value and provide it to vizier.
4. Then I rerun vizier which uses the updated database/ latest result to make a next suggestion.and so on.

Is this possible to do or is there a better way to accomplish this ? Thanks

**Comment by sagipe** [comment]
Hi,

Yes, this is possible.
What you would need to do is:
1. Run a Vizier server with a persistent database. OSS Vizier Server runs with an in-memory database which is recreated every time you run the server. You could switch it to e.g. a sqlite3 database stored on disk
2. Create the study and ask for a suggestion, that's easiest to do in a Python script
3. Write the parameters to a text file that your C++ code can read
4. Run your C++ program, so it reads the parameters, evaluates the function and writes an output to an output file. Note that you can run the C++ program as a sub-process from the Python script, so the entire optimization loop can be automated
5.  Read the output file from the Python program, complete the trial in Vizier and ask for the next suggestion

If that sounds feasible, I can submit a PR with an example Python script that you could use.

Best,
Sagi

**Comment by bhawandeepsingh** [comment]
Hi Sagi,
Thanks, this reads like it will work for my case, 
I basically need the persistent database as mentioned in your answer.
Can you please provide an example for that ? 
Also it may be hard to automate running the C++ program from the python script since the parameters are provided to the C++ program as macros inside hierarchy of #ifdefs. It will be error-prone to try to script finding the correct instance of the macro to update (it's error prone to do it manually also, but when done manually, I know what I changed and can check/ debug). I also have < 10 macros to update, so it's not thousands of parameters like AI, so I have just been doing it manually. I will look into scripting and validating this, but for your example can you please assume I update C++ files manually and run manually offline.
Thanks a lot for help with this.
Thanks and best regards
Bhawandeep Singh

**Comment by bhawandeepsingh** [comment]
Hi @sagipe 
Thanks for your response. 
Is it possible for you to provide an example of a persistent database ?
Thanks a lot once again.
Thanks and best regards
Bhawandeep Singh

**Comment by bhawandeepsingh** [comment]
Hi @sagipe 
Thanks for your response.
Can you please provide an example using a persistent database ?
Thanks a lot once again.
Thanks and best regards
Bhawandeep Singh

**Comment by sagipe** [comment]
Apologies!

The first thing to do is to setup a persistent database of your choice. This can be a SQL database, or any other database supported by SQLAlchemy.

By default, Vizier server uses a local SQLite database, which is stored to disk, so it is persistent (what I meant above was that if you run our demos in Colab, the file is stored in a RAM disk store, so it is not really persistent, but if you run from a Python script, you get  a persistent database on  a real disk).

The database path is accessible via:
```python
from vizier import service

service.VIZIER_DB_PATH
```
and is defined in code in https://github.com/google/vizier/blob/main/vizier/_src/service/constants.py#L41.

If you run the Vizier server using a Python script, or Colab, the location of that database may change, but you can check it using the code snippet above.

Alternatively, you can supply a database path of your choice to the Vizier server via:
```python
from vizier.service import servers

server = servers.DefaultVizierServer(database_url='FILL THIS IN')
```
See https://github.com/google/vizier/blob/main/vizier/_src/service/vizier_server.py#L51 for reference.

The only thing you need to do is to write a small Python main file with the code from above creating a server, and perhaps block so your main file doesn't terminate:

```python
from vizier.service import servers

def serve():
    server = servers.DefaultVizierServer(database_url='FILL THIS IN')
    server._server.wait_for_termination()

if __name__ == "__main__":
    serve()
```

Does this clarify things?

Best,
Sagi

**Comment by bhawandeepsingh** [comment]
Thanks @sagipe 
I can make progress with this. 
Thanks
