### ISSUE TITLE
How to set the port for Default Vizier Server

### ISSUE THREAD

**Issue by jt269** [google/vizier#1098]
Hello,

I am trying to set the port for Vizier server (due to firewall) however it looks like an unused port is selected by default. Is there a way to define the port?

Thanks

**Comment by xingyousong** [comment]
Hi, sorry for the delayed response; 

You can "hack" it by setting the private variable `_port` to one of your choosing: https://github.com/google/vizier/blob/main/vizier/_src/service/vizier_server.py#L62
