### ISSUE TITLE
Specifiy hyperparameters manually

### ISSUE THREAD

**Issue by middleyuan** [google/vizier#1168]
Dear contributors,

Thanks for creating this useful package. I wonder if the feature that allows for manual hyperparameter specification can be released in the future. Instead of optimizing from scratch, it makes sense to inform the optimizer of prior knowledge of hand-tuned hyperparameters. 

Regards,
Tsung

**Comment by xingyousong** [comment]
Hi @middleyuan, you can warm-start the optimizer with previous evaluations `(hyperparameters1, metrics1), (hyperparameters2, metrics2), ...`. 

This can be done using the client with `_add_trial(...)`: https://github.com/google/vizier/blob/main/vizier/_src/service/clients.py#L155
