### ISSUE TITLE
Dealing with duplicates and failed evaluations

### ISSUE THREAD

**Issue by clementruhm** [google/vizier#1199]
Hi!

For the default designers (GPUCBPEBandit and GPBandit) what is the recommended way to deal with duplicates? If the same set of parameters is suggested again? Should I:
a) store metrics from previous runs and complete trials using cached metric?
b) sample another trial to save time?

Is there a way to hop out cycle of the duplicated set of parameters being suggested? For example dynamically increase exploration?

Another question, for the trials that fail, how do I report back that the set of parameters is invalid? i do:
```
trial.complete(vz.Measurement(), infeasibility_reason="invalid_config")
designer.update(vza.CompletedTrials([trial]), vza.ActiveTrials())
```

Is it a valid approach? Is there a better one?

Kind regards

**Comment by xingyousong** [comment]
On duplicates: Can I ask what search space you have? Duplicates occurring might make sense if the search space is a small categorical space (with finitely many possibilities), but it would be shocking if this occurred with a continuous / DOUBLE search space.

On failed trials: Yes, you would mark the trial as infeasible with `infeasibility_reason`. But from your code snippet, you seem to be using the `designer` in a custom loop (rather than using our client API) - can I ask the reason for this?

**Comment by xingyousong** [comment]
On exploration over categorical search spaces : 

Thanks for raising this up, but it's still surprising, given that [our paper](https://arxiv.org/abs/2408.11527) found that we outperform all other industry baselines. If anything, it suggests that this duplication issue would happen _even more_ in other algorithms.

The easiest for you as the user to try would be:

1. Increase the [UCB coefficient](https://github.com/google/vizier/blob/main/vizier/_src/algorithms/designers/gp_ucb_pe.py#L492) to improve exploration
2. Disable the [trust region](https://github.com/google/vizier/blob/main/vizier/_src/algorithms/designers/gp_ucb_pe.py#L489), which normally enforces that suggestions should be close to previous trials.

Give these a shot, and please do let us know what happens, as this helps us improve the algorithm.

**Comment by xingyousong** [comment]
@clementruhm By the way, do you mind showing the exact search space code you're creating? We believe duplications generally shouldn't even happen for categoricals.

We're curious if we can get our hands dirty with what's happening (e.g. we re-create the search space with random objective values and run loops ourselves).

**Comment by clementruhm** [comment]
closing in favor of https://github.com/google/vizier/issues/1204
