### ISSUE TITLE
Algorithms supporting conditional search spaces

### ISSUE THREAD

**Issue by niemiaszek** [google/vizier#1201]
At this moment, none of algorithms is supporting conditional search spaces, as for my scanning through docs and ValueErrors for designers.

Are conditional search spaces selling point for Vertex version of Vizier, or are you planning to add support for them in any algorithm of OSS version?

I'm just starting with Vizier and I was really excited to try out this feature, but seems it's not possible even with grid search approach. For basic tasks similar goals are achievable by using `Infeasibility` property of Vizier, but it would certainly be nice to use conditional search spaces.

**Comment by xingyousong** [comment]
Hi yes, Vertex Vizier is the only one which supports GP-based algorithms for conditional spaces, and thus OSS Vizier GPBandit variants will never support them.

As for random search / grid search, we could support conditionals, although this will take a while.
