### ISSUE TITLE
Typing module considered unnecessary

### ISSUE THREAD

**Issue by reiyw** [google/vizier#272]
As written in `setup.py`, google-vizier requires Python 3.9 or higher:

https://github.com/google/vizier/blob/990c23fce3450b220a9110c53769263d20524251/setup.py#L89

On the other hand, `requirements.txt` requires the installation of the typing module:

https://github.com/google/vizier/blob/990c23fce3450b220a9110c53769263d20524251/requirements.txt#L8

Since the typing module is a backport of the standard library typing module to Python versions older than 3.5, it is not considered necessary to install it. Indeed, this usually does not cause problems since the modules in the standard library take precedence when there is a module with the same name. However, there is no reason to keep unnecessary dependencies, so I'd suggest removing dependency on the typing module:

```diff
diff --git a/requirements.txt b/requirements.txt
index 95e07c3..a659286 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -5,7 +5,6 @@ coverage>=4.5,<=6.4.2
 protobuf>=3.6,<4.0
 mock>=3.0,<=4.0.3
 pytype>=2022.3.8,<=2022.4.22
-typing  # version dependent on Python version.
 grpcio>=1.35.0,<=1.47.0
 portpicker==1.3.1
 pytest  # Use the latest version to match github workflow.
```

**Comment by xingyousong** [comment]
Done, thanks! https://github.com/google/vizier/commit/4329daed2dc6d28a191c6f8123cfa3e1d83bd511
