### ISSUE TITLE
Where is the code implementation for the search algorithms?

### ISSUE THREAD

**Issue by grantlj** [google/vizier#28]
In the study config file, there are multiple search algorithms like: 

ALGORITHM_UNSPECIFIED = study_pb2.StudySpec.Algorithm.ALGORITHM_UNSPECIFIED
  GAUSSIAN_PROCESS_BANDIT = study_pb2.StudySpec.Algorithm.GAUSSIAN_PROCESS_BANDIT
  GRID_SEARCH = study_pb2.StudySpec.Algorithm.GRID_SEARCH
  RANDOM_SEARCH = study_pb2.StudySpec.Algorithm.RANDOM_SEARCH
  NSGA2 = study_pb2.StudySpec.Algorithm.NSGA2
  EMUKIT_GP_EI = study_pb2.StudySpec.Algorithm.EMUKIT_GP_EI

wondering where is the implementation of each algorithm? are they currently not open-sourced?

**Comment by sagipe** [comment]
Hi Liu,

This repository is still work in progress (hence the reason we did not make public announcements about it yet).
We will open source algorithm implementations in the coming months, so stay tuned!

One of the advantages of Vizier is that it's possible to plug-in existing algorithms into it (e.g. https://emukit.github.io/), and use various open-source implementations through a unified client API.
We are also open sourcing our developer APIs, so users will be able to contribute algorithm implementations to Vizier by using our building blocks.

Best,
Sagi

**Comment by sagipe** [comment]
To clarify: you can find implementations of random search, NSGA2 and Emukit as Vizier policies, if you follow the code in [vizier_server.py](https://github.com/google/vizier/blob/main/vizier/service/vizier_server.py).
Check the `policy_creator()` method, and you can follow the algorithm implementations from there.

The code is under `vizier/_src/algorithms/` though this location may change in the future (it's under a private `_src` directory).

Best,
Sagi

**Comment by xingyousong** [comment]
Hi @grantlj, we're happy to announce that all of the algorithm enums are now available in version 0.1.0.
