### ISSUE TITLE
Get suggestions based on existing measurements

### ISSUE THREAD

**Issue by Ark-kun** [google/vizier#284]
What is the easiest way to get Vizier suggestions based on existing measurements? I believe that somewhere inside Vizier there is a something that would let me do this without much overhead or boilerplate.

**Comment by xingyousong** [comment]
Hi @Ark-kun, there are a few ways, depending on how far down stack you're interested in.

At the highest level, you'd use the [User API](https://oss-vizier.readthedocs.io/en/latest/guides/user/running_vizier.html) to tune your tasks and obtain suggestions.

However, if you're purely interested in the algorithm implementations, this would be the [Designer API](https://oss-vizier.readthedocs.io/en/latest/guides/developer/writing_algorithms.html), with our currently implemented designers found [here](https://github.com/google/vizier/tree/main/vizier/_src/algorithms/designers), with their enumerations in the service [here](https://github.com/google/vizier/blob/main/vizier/service/pythia_server.py#L40-L68).

**Comment by Ark-kun** [comment]
>At the highest level, you'd use the [User API](https://oss-vizier.readthedocs.io/en/latest/guides/user/running_vizier.html) to tune your tasks and obtain suggestions.

It looks like this route involves starting a new server and communicating with it's endpoint. This looks like a bit of overhead. 

I've read the documentation about Policies, Designers, Pythia, but I'm still somewhat confused.

`Policy` does not seem to fit since it's geared towards long-term multi-stage operation. Policy seems to be related to asking for suggestions multiple times while I only need to ask once.

`Designer` seems a bit closer, but it seems to be just an abstract interface. The documentation shows how I can create my own `Designer` while I just want to use Vizier's designer. To implement a designer I need to write my own `make_parameters` function. But it looks like that function is what I'm actually seeking. However the sample `make_parameters` function in the documentation is very limited and rudimentary. I need a full-fledged one.

I need Vizier's `make_parameters` function.

**Comment by xingyousong** [comment]
Ah I see what you mean - currently the Default Vizier algorithm (i.e. specific version of Bayesian Optimization, GP-UCB) is still a work in progress, as we're trying to port the C++ version (that's used internally) into Python + Jax. Please stay tuned, as this will be released in the upcoming weeks!

**Comment by Ark-kun** [comment]
> The currently implemented designers found [here](https://github.com/google/vizier/tree/main/vizier/_src/algorithms/designers), with their enumerations in the service [here](https://github.com/google/vizier/blob/main/vizier/service/pythia_server.py#L40-L68).

Thank you. It looks like your first comment provided what I wanted. It looks like I should be able to instantiate a designer without any additional set-up, then update it with known information and get new suggestions.

> currently the Default Vizier algorithm (i.e. specific version of Bayesian Optimization, GP-UCB) is still a work in progress, as we're trying to port the C++ version (that's used internally) into Python + Jax. Please stay tuned, as this will be released in the upcoming weeks!

Great news. I'll keep tuned.

BTW, here is the way I'm using Vizier. Couple of years ago I've build Kubeflow Pipelines [components](https://github.com/Ark-kun/pipeline_components/blob/1b87c0b/components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py) and [pipelines](https://github.com/Ark-kun/pipeline_components/blob/ef6979f5ff47df6e2375a1ce9e8c4d446b674e9f/components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py#L111) for Google Cloud AI Platform Vizier/Optimizer. Recently I was updating it to Vertex version of Vizier and found this Vizier OSS project. Having a portable stand-alone implementation is great. Thank you a lot for this project!

**Comment by xingyousong** [comment]
> BTW, here is the way I'm using Vizier. Couple of years ago I've build Kubeflow Pipelines [components](https://github.com/Ark-kun/pipeline_components/blob/1b87c0b/components/google-cloud/Optimizer/Suggest_parameter_sets_based_on_measurements/component.py) and [pipelines](https://github.com/Ark-kun/pipeline_components/blob/ef6979f5ff47df6e2375a1ce9e8c4d446b674e9f/components/google-cloud/Optimizer/_samples/multi_stage_optimization_atomic_pipeline.py#L111) for Google Cloud AI Platform Vizier/Optimizer. Recently I was updating it to Vertex version of Vizier and found this Vizier OSS project.

Good to know! I'm not sure if it helps, but if your pipeline uses the [OSS Platform Client](https://github.com/google/vizier/blob/main/vizier/service/clients.py), then it should be very easy to switch back-and-forth between OSS and Vertex, as they all follow the same [Cross-Platform abstraction](https://github.com/google/vizier/blob/main/vizier/client/client_abc.py).
