### ISSUE TITLE
pip install google-vizier[jax] failed

### ISSUE THREAD

**Issue by CXCellTrack** [google/vizier#519]
here's the error info:
C:\Users\xxxx>python -V
Python 3.10.9

C:\Users\xxxx>pip install google-vizier[jax]
Collecting google-vizier[jax]
  Using cached google_vizier-0.1.1-py3-none-any.whl (529 kB)
Collecting grpcio-tools<=1.48.2,>=1.35.0
  Using cached grpcio_tools-1.48.2-cp310-cp310-win_amd64.whl (1.9 MB)
Collecting googleapis-common-protos>=1.56.4
  Using cached googleapis_common_protos-1.58.0-py2.py3-none-any.whl (223 kB)
Requirement already satisfied: numpy>=1.21.5 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.24.2)
Collecting absl-py>=1.0.0
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting portpicker>=1.3.1
  Using cached portpicker-1.5.2-py3-none-any.whl (14 kB)
Collecting attrs==21.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting protobuf<4.0,>=3.6
  Using cached protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
Collecting grpcio<=1.48.2,>=1.35.0
  Using cached grpcio-1.48.2-cp310-cp310-win_amd64.whl (3.6 MB)
Collecting sqlalchemy==1.4
  Using cached SQLAlchemy-1.4.0.tar.gz (7.4 MB)
  Preparing metadata (setup.py) ... done
Collecting flax>=0.6.4
  Using cached flax-0.6.5-py3-none-any.whl (209 kB)
Collecting jax>=0.4.2
  Using cached jax-0.4.3.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting google-vizier[jax]
  Using cached google_vizier-0.1.0-py3-none-any.whl (529 kB)
  Using cached google_vizier-0.0.20-py3-none-any.whl (482 kB)
  Using cached google_vizier-0.0.19-py3-none-any.whl (440 kB)
  Using cached google_vizier-0.0.18-py3-none-any.whl (436 kB)
Collecting coverage<=6.4.2,>=4.5
  Using cached coverage-6.4.2-cp310-cp310-win_amd64.whl (187 kB)
Collecting google-api-python-client>=2.65.0
  Using cached google_api_python_client-2.77.0-py2.py3-none-any.whl (11.0 MB)
Collecting mock<=4.0.3,>=3.0
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting pytest
  Using cached pytest-7.2.1-py3-none-any.whl (317 kB)
Collecting pytype>=2022.10.26
  Using cached pytype-2023.2.9.tar.gz (2.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting google-vizier[jax]
  Using cached google_vizier-0.0.17-py3-none-any.whl (432 kB)
  Using cached google_vizier-0.0.16-py3-none-any.whl (421 kB)
  Using cached google_vizier-0.0.15-py3-none-any.whl (419 kB)
  Using cached google_vizier-0.0.14-py3-none-any.whl (418 kB)
  Using cached google_vizier-0.0.13-py3-none-any.whl (390 kB)
  Using cached google_vizier-0.0.12-py3-none-any.whl (390 kB)
  Using cached google_vizier-0.0.11-py3-none-any.whl (388 kB)
Collecting grpcio<=1.47.0,>=1.35.0
  Using cached grpcio-1.47.0-cp310-cp310-win_amd64.whl (3.5 MB)
Collecting googleapis-common-protos==1.56.0
  Using cached googleapis_common_protos-1.56.0-py2.py3-none-any.whl (241 kB)
Collecting portpicker==1.3.1
  Using cached portpicker-1.3.1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting grpcio-tools<=1.47.0,>=1.35.0
  Using cached grpcio_tools-1.47.0-cp310-cp310-win_amd64.whl (1.9 MB)
Collecting pytype<=2022.4.22,>=2022.3.8
  Using cached pytype-2022.4.22.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting google-api-python-client==1.12.8
  Using cached google_api_python_client-1.12.8-py2.py3-none-any.whl (61 kB)
Collecting google-vizier[jax]
  Using cached google_vizier-0.0.10-py3-none-any.whl (303 kB)
Collecting numpy==1.21.5
  Using cached numpy-1.21.5-cp310-cp310-win_amd64.whl (14.0 MB)
Collecting absl-py<1.0,>=0.7
  Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
Collecting typing
  Using cached typing-3.7.4.3.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting google-vizier[jax]
  Using cached google_vizier-0.0.6-py3-none-any.whl (285 kB)
  Using cached google_vizier-0.0.5-py3-none-any.whl (272 kB)
  Using cached google_vizier-0.0.4-py3-none-any.whl (246 kB)
ERROR: Cannot install google-vizier[jax]==0.0.10, google-vizier[jax]==0.0.11, google-vizier[jax]==0.0.12, google-vizier[jax]==0.0.13, google-vizier[jax]==0.0.14, google-vizier[jax]==0.0.15, google-vizier[jax]==0.0.16, google-vizier[jax]==0.0.17, google-vizier[jax]==0.0.18, google-vizier[jax]==0.0.19, google-vizier[jax]==0.0.20, google-vizier[jax]==0.0.4, google-vizier[jax]==0.0.5, google-vizier[jax]==0.0.6, google-vizier[jax]==0.1.0 and google-vizier[jax]==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    google-vizier[jax] 0.1.1 depends on jaxlib>=0.4.2; extra == "jax"
    google-vizier[jax] 0.1.0 depends on jaxlib>=0.4.2; extra == "jax"
    google-vizier[jax] 0.0.20 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.19 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.18 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.17 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.16 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.15 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.14 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.13 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.12 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.11 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.10 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.6 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.5 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.4 depends on jaxlib==0.3.15; extra == "jax"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by xingyousong** [comment]
Hi @CXCellTrack, thanks for raising this. I'm seeing that for some reason, pip cached previous (experimental) versions of `google-vizier` which is causing the conflicts - is it possible to perform a fresh install? 

i.e. can you make sure: 

1. `google-vizier` is completely uninstalled via `pip uninstall google-vizier`
2. The cache is reset via `pip cache purge`? 
3. Reinstallation without caching via `pip --no-cache-dir install google-vizier==0.1.1`?

**Comment by CXCellTrack** [comment]
thank you for your reply, i follow your steps and succeed to install, but when i try to run the example code, it raise errors:
```
Traceback (most recent call last):
  File "D:\pycharm_workspace\blackbox_opt\main.py", line 19, in <module>
    suggestions = study.suggest(count=1)
  File "D:\miniforge3\lib\site-packages\vizier\service\clients.py", line 150, in suggest
    for t in self._client.get_suggestions(
  File "D:\miniforge3\lib\site-packages\vizier\service\vizier_client.py", line 176, in get_suggestions
    operation = self._service.SuggestTrials(request)
  File "D:\miniforge3\lib\site-packages\vizier\service\vizier_service.py", line 388, in SuggestTrials
    suggest_decision_proto = temp_pythia_service.Suggest(
  File "D:\miniforge3\lib\site-packages\vizier\service\pythia_service.py", line 67, in Suggest
    pythia_policy = self._policy_factory(
  File "D:\miniforge3\lib\site-packages\vizier\service\policy_factory.py", line 57, in __call__
    from vizier._src.algorithms.designers import gp_bandit
  File "D:\miniforge3\lib\site-packages\vizier\_src\algorithms\designers\gp_bandit.py", line 32, in <module>
    import chex
ModuleNotFoundError: No module named 'chex'
```
so i think maybe i should use `pip install google-vizier[jax]`?  but found the same error like before:
```
C:\Users\yadong.cx>pip --no-cache-dir install google-vizier==0.1.1
Collecting google-vizier==0.1.1
  Downloading google_vizier-0.1.1-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.9/529.9 kB 1.2 MB/s eta 0:00:00
Collecting grpcio<=1.48.2,>=1.35.0
  Downloading grpcio-1.48.2-cp310-cp310-win_amd64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 8.8 MB/s eta 0:00:00
Collecting protobuf<4.0,>=3.6
  Downloading protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 904.0/904.0 kB 14.2 MB/s eta 0:00:00
Collecting attrs==21.4.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB ? eta 0:00:00
Collecting portpicker>=1.3.1
  Downloading portpicker-1.5.2-py3-none-any.whl (14 kB)
Collecting grpcio-tools<=1.48.2,>=1.35.0
  Downloading grpcio_tools-1.48.2-cp310-cp310-win_amd64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.1 MB/s eta 0:00:00
Collecting absl-py>=1.0.0
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB ? eta 0:00:00
Collecting googleapis-common-protos>=1.56.4
  Downloading googleapis_common_protos-1.58.0-py2.py3-none-any.whl (223 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.0/223.0 kB ? eta 0:00:00
Collecting sqlalchemy==1.4
  Downloading SQLAlchemy-1.4.0.tar.gz (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 16.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.21.5 in d:\miniforge3\lib\site-packages (from google-vizier==0.1.1) (1.24.2)
Collecting greenlet!=0.4.17
  Downloading greenlet-2.0.2-cp310-cp310-win_amd64.whl (192 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.2/192.2 kB ? eta 0:00:00
Requirement already satisfied: six>=1.5.2 in d:\miniforge3\lib\site-packages (from grpcio<=1.48.2,>=1.35.0->google-vizier==0.1.1) (1.16.0)
Requirement already satisfied: setuptools in d:\miniforge3\lib\site-packages (from grpcio-tools<=1.48.2,>=1.35.0->google-vizier==0.1.1) (65.6.3)
Collecting psutil
  Downloading psutil-5.9.4-cp36-abi3-win_amd64.whl (252 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.5/252.5 kB 16.1 MB/s eta 0:00:00
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.4.0-cp310-cp310-win_amd64.whl size=1449117 sha256=38da66a70b6e267fe8487429b1e1558bfba4968e0c1425bd6a01323439d8b729
  Stored in directory: C:\Users\yadong.cx\AppData\Local\Temp\pip-ephem-wheel-cache-r06sv3__\wheels\22\8a\e1\9d63ce4e250a5dac944b29832f98ca73bd9984ae7011b12ea7
Successfully built sqlalchemy
Installing collected packages: psutil, protobuf, grpcio, greenlet, attrs, absl-py, sqlalchemy, portpicker, grpcio-tools, googleapis-common-protos, google-vizier
Successfully installed absl-py-1.4.0 attrs-21.4.0 google-vizier-0.1.1 googleapis-common-protos-1.58.0 greenlet-2.0.2 grpcio-1.48.2 grpcio-tools-1.48.2 portpicker-1.5.2 protobuf-3.20.3 psutil-5.9.4 sqlalchemy-1.4.0

C:\Users\yadong.cx>pip uninstall google-vizier
Found existing installation: google-vizier 0.1.1
Uninstalling google-vizier-0.1.1:
  Would remove:
    d:\miniforge3\lib\site-packages\google_vizier-0.1.1.dist-info\*
    d:\miniforge3\lib\site-packages\vizier\*
Proceed (Y/n)? y
  Successfully uninstalled google-vizier-0.1.1

C:\Users\yadong.cx>pip cache purge
Files removed: 32

C:\Users\xxxx>pip --no-cache-dir install google-vizier[jax]
Collecting google-vizier[jax]
  Downloading google_vizier-0.1.1-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.9/529.9 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: portpicker>=1.3.1 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.5.2)
Requirement already satisfied: protobuf<4.0,>=3.6 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (3.20.3)
Requirement already satisfied: absl-py>=1.0.0 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.4.0)
Requirement already satisfied: numpy>=1.21.5 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.24.2)
Requirement already satisfied: googleapis-common-protos>=1.56.4 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.58.0)
Requirement already satisfied: grpcio-tools<=1.48.2,>=1.35.0 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.48.2)
Requirement already satisfied: attrs==21.4.0 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (21.4.0)
Requirement already satisfied: grpcio<=1.48.2,>=1.35.0 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.48.2)
Requirement already satisfied: sqlalchemy==1.4 in d:\miniforge3\lib\site-packages (from google-vizier[jax]) (1.4.0)
  Downloading google_vizier-0.1.0-py3-none-any.whl (529 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 3.7 MB/s eta 0:00:00
  Downloading google_vizier-0.0.20-py3-none-any.whl (482 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 482.0/482.0 kB 3.8 MB/s eta 0:00:00
  Downloading google_vizier-0.0.19-py3-none-any.whl (440 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 3.9 MB/s eta 0:00:00
  Downloading google_vizier-0.0.18-py3-none-any.whl (436 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 436.8/436.8 kB 3.9 MB/s eta 0:00:00
Collecting mock<=4.0.3,>=3.0
  Downloading mock-4.0.3-py3-none-any.whl (28 kB)
Collecting pytype>=2022.10.26
  Downloading pytype-2023.2.14.tar.gz (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytest
  Downloading pytest-7.2.1-py3-none-any.whl (317 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 kB 3.9 MB/s eta 0:00:00
Collecting google-api-python-client>=2.65.0
  Downloading google_api_python_client-2.78.0-py2.py3-none-any.whl (11.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 3.9 MB/s eta 0:00:00
Collecting coverage<=6.4.2,>=4.5
  Downloading coverage-6.4.2-cp310-cp310-win_amd64.whl (187 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 187.5/187.5 kB 3.8 MB/s eta 0:00:00
Collecting google-vizier[jax]
  Downloading google_vizier-0.0.17-py3-none-any.whl (432 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.4/432.4 kB 3.9 MB/s eta 0:00:00
  Downloading google_vizier-0.0.16-py3-none-any.whl (421 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.9/421.9 kB 4.4 MB/s eta 0:00:00
  Downloading google_vizier-0.0.15-py3-none-any.whl (419 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 4.4 MB/s eta 0:00:00
  Downloading google_vizier-0.0.14-py3-none-any.whl (418 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 418.4/418.4 kB 4.3 MB/s eta 0:00:00
  Downloading google_vizier-0.0.13-py3-none-any.whl (390 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.6/390.6 kB 4.1 MB/s eta 0:00:00
  Downloading google_vizier-0.0.12-py3-none-any.whl (390 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 390.6/390.6 kB 4.0 MB/s eta 0:00:00
  Downloading google_vizier-0.0.11-py3-none-any.whl (388 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.7/388.7 kB 4.0 MB/s eta 0:00:00
Collecting googleapis-common-protos==1.56.0
  Downloading googleapis_common_protos-1.56.0-py2.py3-none-any.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.5/241.5 kB 4.9 MB/s eta 0:00:00
Collecting portpicker==1.3.1
  Downloading portpicker-1.3.1.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting pytype<=2022.4.22,>=2022.3.8
  Downloading pytype-2022.4.22.tar.gz (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting grpcio-tools<=1.47.0,>=1.35.0
  Downloading grpcio_tools-1.47.0-cp310-cp310-win_amd64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 4.1 MB/s eta 0:00:00
Collecting google-api-python-client==1.12.8
  Downloading google_api_python_client-1.12.8-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.2 MB/s eta 0:00:00
Collecting grpcio<=1.47.0,>=1.35.0
  Downloading grpcio-1.47.0-cp310-cp310-win_amd64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 4.0 MB/s eta 0:00:00
Collecting google-vizier[jax]
  Downloading google_vizier-0.0.10-py3-none-any.whl (303 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.5/303.5 kB 4.7 MB/s eta 0:00:00
Collecting absl-py<1.0,>=0.7
  Downloading absl_py-0.15.0-py3-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 kB 7.6 MB/s eta 0:00:00
Collecting typing
  Downloading typing-3.7.4.3.tar.gz (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy==1.21.5
  Downloading numpy-1.21.5-cp310-cp310-win_amd64.whl (14.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 5.5 MB/s eta 0:00:00
Collecting google-vizier[jax]
  Downloading google_vizier-0.0.6-py3-none-any.whl (285 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.6/285.6 kB 5.9 MB/s eta 0:00:00
  Downloading google_vizier-0.0.5-py3-none-any.whl (272 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 272.5/272.5 kB 8.5 MB/s eta 0:00:00
  Downloading google_vizier-0.0.4-py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.9/246.9 kB 7.6 MB/s eta 0:00:00
ERROR: Cannot install google-vizier[jax]==0.0.10, google-vizier[jax]==0.0.11, google-vizier[jax]==0.0.12, google-vizier[jax]==0.0.13, google-vizier[jax]==0.0.14, google-vizier[jax]==0.0.15, google-vizier[jax]==0.0.16, google-vizier[jax]==0.0.17, google-vizier[jax]==0.0.18, google-vizier[jax]==0.0.19, google-vizier[jax]==0.0.20, google-vizier[jax]==0.0.4, google-vizier[jax]==0.0.5, google-vizier[jax]==0.0.6, google-vizier[jax]==0.1.0 and google-vizier[jax]==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    google-vizier[jax] 0.1.1 depends on jaxlib>=0.4.2; extra == "jax"
    google-vizier[jax] 0.1.0 depends on jaxlib>=0.4.2; extra == "jax"
    google-vizier[jax] 0.0.20 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.19 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.18 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.17 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.16 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.15 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.14 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.13 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.12 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.11 depends on jaxlib>=0.3.15; extra == "jax"
    google-vizier[jax] 0.0.10 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.6 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.5 depends on jaxlib==0.3.15; extra == "jax"
    google-vizier[jax] 0.0.4 depends on jaxlib==0.3.15; extra == "jax"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by xingyousong** [comment]
Ah sorry, what I meant was `google-vizier[jax]` for everything, i.e. can you try again: 

1. `google-vizier[jax]` is completely uninstalled via `pip uninstall google-vizier[jax]`; to be extra sure, can you also `pip uninstall` all packages in `requirements-jax.txt`?
2. The cache is reset via pip cache purge?
3. Reinstallation without caching via pip --no-cache-dir install google-vizier[jax]==0.1.1?

**Comment by CXCellTrack** [comment]
@xingyousong i have tried but it does not work, besides, i find that jaxlib does not have a windows whl file, maybe it's the final reason:
https://pypi.org/project/jaxlib/#files

**Comment by emilyfertig** [comment]
@CXCellTrack What if you follow those steps, but then `pip install chex` before running the example code?

**Comment by BYTERHIT** [comment]
@emilyfertig your advise works. But I got other error message when testing. Anyone knows how to fix it?
[log_vizier.txt](https://github.com/google/vizier/files/10822234/log_vizier.txt)

**Comment by xingyousong** [comment]
FYI `google-vizier` has been updated to 0.1.2 which contains potential fixes to these issues - can you try the test again?

**Comment by BYTERHIT** [comment]
v0.1.2 works.

**Comment by xingyousong** [comment]
@BYTERHIT great! I'm going to close this thread for now then, unless more issues pop up.
