### ISSUE TITLE
Python 3.8: field() got an unexpected keyword argument 'kw_only'

### ISSUE THREAD

**Issue by gadfort** [google/vizier#803]
google-vizier-0.1.6

When installing from PIP using Python3.8 and then running, this is the error:
```
  File "/home/../.local/lib/python3.8/site-packages/vizier/_src/jax/models/tuned_gp_models.py", line 79, in VizierGaussianProcess
    _use_retrying_cholesky: bool = struct.field(
  File "/home/../.local/lib/python3.8/site-packages/flax/struct.py", line 31, in field
    return dataclasses.field(metadata={'pytree_node': pytree_node}, **kwargs)
TypeError: field() got an unexpected keyword argument 'kw_only'
```
It looks like the kw_only flag is available in 3.10, but not 3.8

**Comment by qiuyiz** [comment]
Please update to Python 3.10 (as in our requirements) we are no longer supporting 3.8

**Comment by gadfort** [comment]
https://github.com/google/vizier/blob/6224195082c332d886f7710a5b34caa6be0f5e44/setup.py#L103
This is still listed as 3.8, please correct that then

**Comment by xingyousong** [comment]
Hi, to clarify on this - 

The *client* API supports Python 3.8+ (to also allow interacting with Vertex Vizier). 
All service-related API (e.g. the Vizier server and its default GP-bandit algorithm) requires 3.10.

* If running locally (i.e. your machine runs both the client and service), then it'll require 3.10. I believe this is the case you encountered, where the 3.10 requirement shows up when trying to run our GP-Bandit algorithm.

* If running distributed, then your client machine requires 3.8+ only, but the service machine will require 3.10.

**Comment by gadfort** [comment]
@xingyousong thanks for clarifying.
