### ISSUE TITLE
sqlalchemy requeriment is too strict

### ISSUE THREAD

**Issue by mpds** [google/vizier#873]
I'm installing Vizier via pip, but I'm facing an issue with the required version of the sqlalchemy package. Vizier specifically demands  sqlalchemy==1.4, while other packages in my environment need sqlalchemy>=1.4.1. Furthermore, using sqlalchemy version 1.4.1 with Vizier works fine. Could the dependency be made more flexible (e.g., sqalchemy>=1.4.1)?

**Comment by qiuyiz** [comment]
as a workaround, feel free to force-reinstall a higher version of sqlalchemy while we relax the conditions
