### ISSUE TITLE
Seeding the Random Number Generators?

### ISSUE THREAD

**Issue by dreavjr** [google/vizier#902]
Currently, in the documentation, it's unclear whether it's possible to control the RNGs' seeding, and if that's possible, where (server, client, problem, study, sampling?) and how to perform that seeding.

**Comment by sagipe** [comment]
Hi,

Currently, it's only possible to control the RNG seeding at a `Designer` level, which can happen on the server code itself (e.g. in the policy factory code).

Part of what makes Vizier a good global optimizer is that it's stochastic, and we build a new Designer for every batch of trials. We typically only supply the seed when we want to replicate a specific trial that e.g. a user complained about, based on the seed that was used to generate the suggestion (and it stored in the trial metadata).

Do you have a specific use case where you'd want to control the seed from the client side?

Best,
Sagi

**Comment by dreavjr** [comment]
Seeding at the server level would work be totally fine for my use case. Do you have an example (or documentation) on how to use the `Designer` class to accomplish that?

For illustration, this is my current usage:

```python
problem = vz.ProblemStatement()
problem.search_space.root.add_float_param('lr_exp', search_space['lr_exp_min'], search_space['lr_exp_max'])
problem.search_space.root.add_float_param('wd_exp', search_space['wd_exp_min'], search_space['wd_exp_max'])
problem.metric_information.append(vz.MetricInformation(name='dummy_metric', goal=vz.ObjectiveMetricGoal.MAXIMIZE))

study_config = vz.StudyConfig.from_problem(problem)
study_config.algorithm = 'QUASI_RANDOM_SEARCH'

server = servers.DefaultVizierServer(host='localhost', database_url=None)
clients.environment_variables.server_endpoint = server.endpoint
study_client = clients.Study.from_study_config(study_config, owner='owner', study_id = 'example_study_id')

suggestions = study_client.suggest(count=samples_n)
```

**Comment by xingyousong** [comment]
Apologies for the late response - you'll have to modify the code here, which is used by the server to initialize algorithms: https://github.com/google/vizier/blob/e35c2cb4512399a8d78d57a2f780d8013f4a8bd4/vizier/_src/service/policy_factory.py#L40-L53

`from_problem` allows a seed.
