### ISSUE TITLE
Getting started example error

### ISSUE THREAD

**Issue by Luisenden** [google/vizier#947]
Hi, I'm using Python 3.9.18 and wanted to test the given getting-started example
when I run the code below, I get the following error: 
`TypeError: field() got an unexpected keyword argument 'kw_only'`

What could be the issue here? 

```from vizier.service import clients
from vizier.service import pyvizier as vz

# Objective function to maximize.
def evaluate(w: float, x: int, y: float, z: str) -> float:
  return w**2 - y**2 + x * ord(z)

# Algorithm, search space, and metrics.
study_config = vz.StudyConfig(algorithm='GAUSSIAN_PROCESS_BANDIT')
study_config.search_space.root.add_float_param('w', 0.0, 5.0)
study_config.search_space.root.add_int_param('x', -2, 2)
study_config.search_space.root.add_discrete_param('y', [0.3, 7.2])
study_config.search_space.root.add_categorical_param('z', ['a', 'g', 'k'])
study_config.metric_information.append(vz.MetricInformation('metric_name', goal=vz.ObjectiveMetricGoal.MAXIMIZE))

# Setup client and begin optimization. Vizier Service will be implicitly created.
study = clients.Study.from_study_config(study_config, owner='my_name', study_id='example')
for i in range(10):
  suggestions = study.suggest(count=1)
  for suggestion in suggestions:
    params = suggestion.parameters
    objective = evaluate(params['w'], params['x'], params['y'], params['z'])
    suggestion.complete(vz.Measurement({'metric_name': objective})) 
```

**Comment by sagipe** [comment]
Hi Luisenden,

You would need Python 3.10 to run this getting started example.
The reason is that while the Vizier client supports Python 3.8+, when running the service, you would need Python 3.10+.

You could, for example, run a distributed Vizier service on a machine that has Python 3.10+, and then use the Python client code from Colab which runs Python 3.9.18

Best,
Sagi

**Comment by Luisenden** [comment]
Hi Sagi, thanks for the prompt reply - I installed `google-vizier[jax]` in a Python 3.10 env on a Mac M2 with Sonoma 14.0 (which should be [supported](https://jax.readthedocs.io/en/latest/installation.html#pip-installation-cpu)).

When running the example, the jax dependency is however giving me troubles: `RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.` 

Building from source then crashed with `subprocess.CalledProcessError: Command '['./bazel-6.1.2-darwin-x86_64', 'run', '--verbose_failures=true', '//jaxlib/tools:build_wheel', '--', '--output_path=/Users/localadmin/Documents/git/jax/dist', '--cpu=x86_64']' returned non-zero exit status 1.`

Do you know any workaround here ?

**Comment by sagipe** [comment]
Jax team is asking if you are using rosetta. If so, please install native Python and try again.
Please let me know if that works.
-Sagi
